# Generated by Django 2.0.dev20170801063841 on 2017-08-01 06:50

from django.conf import settings
from django.db import migrations, models
import editormd.models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_post_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=editormd.models.EditorMdField(),
        ),
    ]
