# Generated by Django 2.0.dev20170801131532 on 2017-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20170801_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='absolute_url',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
