# Generated by Django 2.0.dev20170801131532 on 2017-08-01 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20170801_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='absolute_url',
            new_name='slug',
        ),
    ]
